=== Rigveda

==== Nature and Importance

The Rigveda is the oldest compilation of human wisdom. This Samhita (Collection) is unique in its nature. In fact, it is not a book, but a compilation composed of several books which can be individually distinguished from each other. The present from of this Samhita clearly indicates that the collection is not a single work, but consists of older and later elements. Various indications of language, style and ideas prove this point. Different hymns of this Samhita were composed long before they were systematically arranged. Being a compilation of different stages, there is something which stamps the Rigveda with an individuality of its own. It is much more natural in character and form than other Samhitas.

The Rigveda represents the earliest sacred book of India. It is oldest and biggest amongst all the four Vedas. All the features of Classical Sanskrit poetry can be traced to the Rigveda. In it we find the seeds of India&#8217;s religious and philosophical development. Thus, both for its poetry and its religious and philosophical importance, the Rigveda should be studied by one who wants to understand Indian literature and spiritual culture. The value of the Rigveda today is not confined to India, for its well-preserved language and mythology have helped a better understanding of languages, literatures and cultures of a whole world.

==== Form and Division


The whole of the Rigveda-Samhita is in form of verses, known as Rik.

&#8216;Rik&#8217; is the name given to those Mantras which are meant for the praise of the deities. Thus the collection (Samhita) of Riks is known as Rigveda-Samhita. Only one recession or school (Shakha) of the Rigveda is available today and it is the Shaakala. The Rigveda Samhita contains about 10552 Mantras, classified into ten books called Mandalas. Each Mandala is divided into several sections called Anuvakas. Each Anuvaka consists of a number of hymns called Suktas and each Sukta is made up of a number of verses called riks. This division of the Rigveda is most popular and systematic. There are two ways of dividing the contents of the Rigveda, but today other division is uncommon among the students of the Veda.

A Sukta is a group of Mantras. The number of Mantras in a Sukta is not fixed. Some Suktas have a small number of Mantras while others have a large number of Mantras. It is important to note that every Sukta has a seer i.e. Rishi, a deity i.e. Devata and a metre i.e. Chandas . The Samhita of the Rigveda comprises 10 Mandalas, 85 Anuvakas, 1028 Suktas and 10552 Mantras. Usually Anuvaka is not mentioned for the reference of a Mantra of the Rigveda. For example RV 3.16.7 simply means the seventh Mantra of the sixteenth Sukta of the third Mandala of the Rigveda.</p>
<p>  Through this chart we can know the division of Mandalas, number of Suktas in each Mandala and name of Rishis of some Mandalas.

include::mandala/mandla01.adoc[]
